### ISSUE TITLE
Just loading....

### ISSUE THREAD

**Issue by zsocasog** [richardfous/MMM-NameDay#3]
The module won't start, I think the url has changed of the provider... 
I modified the MMM-NameDay.js with the following and now the module is working:

in row 56
 const baseUrl = "https://api.abalin.net/"; --->  const baseUrl = "https://nameday.abalin.net/";
in row 96
dataRequest.open("GET", url, true); ---> dataRequest.open("POST", url, true);

I have tested only the "today" method, but now it is working.

**Comment by AlienPT** [comment]
I have the same issue - I changed the lines 56 and 96 and it was working.
On next day it was not updated and after MM refresh and also complete reboot it still just "Loading..."
Any ideas?

**Comment by lacee82** [comment]
The same issue here. The first post solved the previous "Loading..." issue, then it's back again.
Hope some experts can advise here. :)

**Comment by AlienPT** [comment]
Any news on this? It's a great and simple module but it's not working...

**Comment by radimkarnis** [comment]
Seems like the API has been changed again. Is this module actively maintained?

**Comment by AlienPT** [comment]
Modules without maintenance should be deleted... Otherwise there are more questions as answers...
And all of us just need to wait... and wait... and nothing... I really hate approach like this...

**Comment by AlienPT** [comment]
Sorry, but still the same... "Loading..." I reinstalled after you updated your repo but it's the same.
Any ideas what can be wrong?
I don't have any special setup just "Country" set to "sk".
Thank you

**Comment by richardfous** [comment]
So it looks like there is a problem with the API. The fix that zsocasog provided should work once the API issues have been resolved. I have already implemented the fix into to master branch. Someone has already opened an issue with the API provider and you can follow the progress here https://github.com/xnekv03/nameday-api/issues/5.

**Comment by AlienPT** [comment]
Thank you very much for the info.

**Comment by lacee82** [comment]
Any update on the API issue?
Or shall I look for an alternative? If yes, any proposal from anybody?

**Comment by richardfous** [comment]
No, still waiting for the API developer to fix the issue. I have tried some workarounds, but nothing worked. If you are able to find some proxy website, that would take care of the CORS problem, feel free to post it here and i can implement it in the code. But i was not able to find such website. As far as i know, there is no similar module, that is able to show name days.

**Comment by lacee82** [comment]
Thanks!
Is there maybe an offline version somehow? I mean the names listed in a TXT or something and the app just looks up the name of the date today...
Basically no need to be this online, namedays are not dinamic inputs...😄

**Comment by AlienPT** [comment]
That is really very good idea make it offline.
Richard,
would it be possible?
It's really good module and there is no other options right now :)

**Comment by richardfous** [comment]
Sure, i can do that. However, it is going take some time to gather name days for all countries. Give me few days and i am going to implement something.

**Comment by AlienPT** [comment]
Excellent :) I can test SK for you :)

**Comment by lacee82** [comment]
Great news! 😄
I can test HU for you! 😊

**Comment by richardfous** [comment]
So, i have added support for offline loading of namedays. There is a new folder called resources, where you can find JSON file that contains all namedays from the API. The offline mode only works if the API is not accessible. I have done a few tests myself and it looks like it is working now.

**Comment by AlienPT** [comment]
Hi Richard,
I can confirm that your module is working again :)
Just one thing - it's correct for TODAY but it shows the same name also for TOMORROW - is it only something on my end or it's working only for TODAY for now?
Anyway thank you very much for you work on this :)

**Comment by richardfous** [comment]
The offline mode was only available with TODAY mode when i released the update. And now you can also use the TOMORROW and YESTERDAY modes.

**Comment by AlienPT** [comment]
And you are absolutely amazing!!!
All is working now as expected :)
Thank you very much - my MM is now complete :)

**Comment by lacee82** [comment]
Great job! Thanks a lot, it works as expected! 🤝🍾😄
